version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_arm_85
      MONGO_INITDB_DATABASE: workdesk
    volumes:
      - ./deploy/prod/mondodb/data_db:/data/db
      - ./deploy/prod/mondodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27018:27017
    networks:
      - app-network
  
  workdesk-backend:
    container_name: workdesk-backend
    restart: always
    build: .
    ports:
      - 3000:8080
    depends_on:
      - mongodb  
    links:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge